[package]
name = "rust-redis"
version = "0.0.1"
edition = "2018"
authors = ["chenkun <chenkun_lws@126.com>"]
description = "Redis re-implemented in Rust"
license-file = "LICENSE"

[workspace]
members = [
    "resp-parser",
]

[dependencies]
