[package]
name = "resp-parser"
version = "0.0.1"
edition = "2018"
authors = ["chenkun <chenkun_lws@126.com>"]
description = "Redis Protocol Parser in Rust"
license-file = "../LICENSE"

[dependencies]
