[package]
name = "rust-skiplist"
version = "0.0.1"
edition = "2018"
authors = ["chenkun <chenkun_lws@126.com>"]
description = "skiplist implemented in rust"
license-file = "../LICENSE"

[dependencies]
